
import java.util.ArrayList;
import javafx.scene.control.ComboBox;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Administrador
 */
public class principal extends javax.swing.JFrame {

    ArrayList<Alumno> nomina = new ArrayList();
    Alumno alumno = new Alumno();
    DefaultTableModel modelo = new DefaultTableModel();

    public principal() {
        initComponents();
        tblListado.setModel(modelo);
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Email");
        modelo.addColumn("Legajo");
        modelo.addColumn("Materia");
        modelo.addColumn("Nota");
        modelo.addColumn(" ");
        tblListado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblLegajo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JComboBox<>();
        lblNota = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        btnAnotarse = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        cmbAlumno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblPromedio = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListado2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListado1 = new javax.swing.JTable();
        lblEmail_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(188, 215, 139));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, -1));

        lblLegajo.setText("Legajo:");
        panelPrincipal.add(lblLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 30));

        lblNombre.setText("Nombre: ");
        panelPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoActionPerformed(evt);
            }
        });
        txtLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegajoKeyTyped(evt);
            }
        });
        panelPrincipal.add(txtLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 190, -1));
        panelPrincipal.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 190, -1));

        jLabel1.setText("Apellido:");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        lblEmail.setText("Email:");
        panelPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 86, -1, 20));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 190, -1));

        lblMateria.setText("Materia: ");
        panelPrincipal.add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));

        txtMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algoritmos II", "Analisis II", "Estadistica", "Sistemas Operativos", "Base de datos" }));
        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, -1));

        lblNota.setText("Nota:");
        panelPrincipal.add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 30));

        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNotaKeyTyped(evt);
            }
        });
        panelPrincipal.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, -1));

        btnAnotarse.setText("Anotarse");
        btnAnotarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnotarseActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnAnotarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 250, -1));

        tblListado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Mail", "Legajo", "Materia", "Nota", ""
            }
        ));
        jScrollPane1.setViewportView(tblListado);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 620, 150));

        cmbAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir alumno" }));
        cmbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlumnoActionPerformed(evt);
            }
        });
        panelPrincipal.add(cmbAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 130, -1));

        jLabel2.setText("Alumno:");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 120, -1));

        lblPromedio.setText("Promedio");
        panelPrincipal.add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, 30));

        txtPromedio.setEnabled(false);
        panelPrincipal.add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 130, -1));

        tblListado2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblListado2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Mail", "Legajo", "Materia", "Nota", ""
            }
        ));
        jScrollPane3.setViewportView(tblListado2);

        scrollPane1.add(jScrollPane3);

        tblListado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblListado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Mail", "Legajo", "Materia", "Nota", ""
            }
        ));
        jScrollPane2.setViewportView(tblListado1);

        scrollPane1.add(jScrollPane2);

        panelPrincipal.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 600, 150));

        lblEmail_error.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEmail_error.setForeground(new java.awt.Color(255, 0, 0));
        panelPrincipal.add(lblEmail_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAnotarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnotarseActionPerformed

        // CREO UN OBJETO ALUMNO y ARRAY STRING
        Alumno altaAlumno = new Alumno();
        String addAlumnoLista[] = new String[6];

        /**
         * ****** RELLENAR EL OBJETO Y CARGARLO EN EL ARRAYLIST* **
         */
        //Relleno el objeto con los datos de cada TextField
        altaAlumno.setLegajo(Integer.parseInt(txtLegajo.getText()));
        altaAlumno.setNombre(txtNombre.getText());
        altaAlumno.setApellido(txtApellido.getText());
        altaAlumno.setEmail(txtEmail.getText());
        altaAlumno.setMateria(String.valueOf(txtMateria.getSelectedItem()));
        altaAlumno.setNota(Integer.parseInt(txtNota.getText()));
        //Agrego el objeto al ArrayList
        nomina.add(altaAlumno);

        /**
         * ****** RELLENAR ARRAY STRING Y SETEARLO EN TABLA INTERFAZ *******
         */
        addAlumnoLista[0] = altaAlumno.getNombre();
        addAlumnoLista[1] = altaAlumno.getApellido();
        addAlumnoLista[2] = altaAlumno.getEmail();
        addAlumnoLista[3] = String.valueOf(altaAlumno.getLegajo());
        addAlumnoLista[4] = altaAlumno.getMateria();
        addAlumnoLista[5] = String.valueOf(altaAlumno.getNota());
        //Cargo la Tabla Interfaz con el Array String
        modelo.addRow(addAlumnoLista);

        /**
         * ********** RELLENAR ComboBox CON APELLIDO SIN REPETIR **************
         */
        if (!existe(addAlumnoLista[1])) {
            cmbAlumno.addItem(addAlumnoLista[1]);
        }
    }//GEN-LAST:event_btnAnotarseActionPerformed

    public boolean existe(String apellido) {
        int size = cmbAlumno.getItemCount();
        for (int i = 0; i < size; i++) {
            String item = cmbAlumno.getItemAt(i);
            if (item.equals(apellido)) {
                return true;
            }
        }
        return false;
    }


    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTxt();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double notas = 0, contador = 0;
        double promedio;
        String ape;

        for (int i = 0; i < nomina.size(); i++) {
            ape = nomina.get(i).getApellido();
            if (ape.equals(String.valueOf(cmbAlumno.getSelectedItem()))) {
                notas += nomina.get(i).getNota();
                contador++;
            }
        }
        promedio = notas / contador;
        if(!(promedio>0 || promedio<10000000)){
            txtPromedio.setText("");
        }else{ txtPromedio.setText(String.valueOf(promedio));
        }
       
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked


    }//GEN-LAST:event_btnCalcularMouseClicked

    private void cmbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlumnoActionPerformed

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoActionPerformed

    private void txtLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLegajoKeyTyped

        soloNumeros(evt);
    }//GEN-LAST:event_txtLegajoKeyTyped

    private void txtNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_txtNotaKeyTyped

    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }

    private void limpiarTxt() {
        txtApellido.setText("");
        txtNombre.setText("");
        txtLegajo.setText("");
        txtEmail.setText("");
        txtNota.setText("");
        txtNombre.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnotarse;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail_error;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JPanel panelPrincipal;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tblListado;
    private javax.swing.JTable tblListado1;
    private javax.swing.JTable tblListado2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JComboBox<String> txtMateria;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
