/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrador
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnGrupos = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lbTarifa = new javax.swing.JLabel();
        lblTituloTarifa = new javax.swing.JLabel();
        btnLocal = new javax.swing.JRadioButton();
        btnMerco = new javax.swing.JRadioButton();
        btnExtran = new javax.swing.JRadioButton();
        checkEstudiante = new javax.swing.JCheckBox();
        checkJubilado = new javax.swing.JCheckBox();
        checkBrasil = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Cataratas del Iguazu");

        lbTarifa.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lbTarifa.setForeground(new java.awt.Color(51, 51, 51));
        lbTarifa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTarifa.setToolTipText("");
        lbTarifa.setAlignmentX(0.5F);
        lbTarifa.setAutoscrolls(true);
        lbTarifa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloTarifa.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblTituloTarifa.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloTarifa.setText("Tarifa");

        btnGrupos.add(btnLocal);
        btnLocal.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnLocal.setForeground(new java.awt.Color(51, 51, 51));
        btnLocal.setText("Local");
        btnLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLocalMouseClicked(evt);
            }
        });
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });

        btnGrupos.add(btnMerco);
        btnMerco.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnMerco.setForeground(new java.awt.Color(51, 51, 51));
        btnMerco.setText("Mercosur");
        btnMerco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMercoMouseClicked(evt);
            }
        });
        btnMerco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercoActionPerformed(evt);
            }
        });

        btnGrupos.add(btnExtran);
        btnExtran.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnExtran.setForeground(new java.awt.Color(51, 51, 51));
        btnExtran.setText("Extranjero");
        btnExtran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExtranMouseClicked(evt);
            }
        });
        btnExtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtranActionPerformed(evt);
            }
        });

        checkEstudiante.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        checkEstudiante.setForeground(new java.awt.Color(51, 51, 51));
        checkEstudiante.setText("Estudiante");
        checkEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkEstudiante.setEnabled(false);
        checkEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkEstudianteMouseClicked(evt);
            }
        });
        checkEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstudianteActionPerformed(evt);
            }
        });

        checkJubilado.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        checkJubilado.setForeground(new java.awt.Color(51, 51, 51));
        checkJubilado.setText("Jubilado");
        checkJubilado.setEnabled(false);
        checkJubilado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkJubiladoMouseClicked(evt);
            }
        });

        checkBrasil.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        checkBrasil.setForeground(new java.awt.Color(51, 51, 51));
        checkBrasil.setText("Brasilero");
        checkBrasil.setEnabled(false);
        checkBrasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBrasilMouseClicked(evt);
            }
        });
        checkBrasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBrasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMerco)
                    .addComponent(btnExtran)
                    .addComponent(btnLocal))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTituloTarifa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkJubilado)
                        .addComponent(checkEstudiante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBrasil)
                        .addGap(11, 11, 11)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnLocal)
                        .addGap(21, 21, 21)
                        .addComponent(btnMerco)
                        .addGap(18, 18, 18)
                        .addComponent(btnExtran))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloTarifa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkEstudiante)
                                .addGap(18, 18, 18)
                                .addComponent(checkJubilado)
                                .addGap(18, 18, 18)
                                .addComponent(checkBrasil)))
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
        checkBrasil.setEnabled(false);
        checkEstudiante.setEnabled(false);
        checkJubilado.setEnabled(false);
        checkBrasil.setSelected(false);
        checkJubilado.setSelected(false);
        checkEstudiante.setSelected(false);
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnMercoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercoActionPerformed
            
        checkBrasil.setEnabled(true);
        checkEstudiante.setEnabled(true);
        checkJubilado.setEnabled(true);
        
    }//GEN-LAST:event_btnMercoActionPerformed

    private void checkEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEstudianteActionPerformed

    private void checkBrasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBrasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBrasilActionPerformed

    private void btnLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocalMouseClicked
        if (btnLocal.isSelected()) {
            lbTarifa.setText("Sin cargo");
        }
    }//GEN-LAST:event_btnLocalMouseClicked

    private void btnMercoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMercoMouseClicked
        if (btnMerco.isSelected()) {
            lbTarifa.setText("200");
        }
    }//GEN-LAST:event_btnMercoMouseClicked

    private void btnExtranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtranMouseClicked
        if (btnExtran.isSelected()) {
            lbTarifa.setText("1000");
        }
    }//GEN-LAST:event_btnExtranMouseClicked

    private void btnExtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtranActionPerformed
        checkBrasil.setEnabled(false);
        checkEstudiante.setEnabled(false);
        checkJubilado.setEnabled(false);
        checkBrasil.setSelected(false);
        checkJubilado.setSelected(false);
        checkEstudiante.setSelected(false);
    }//GEN-LAST:event_btnExtranActionPerformed


    private void checkEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkEstudianteMouseClicked
        if (btnMerco.isSelected() && checkEstudiante.isSelected()) {
            checkBrasil.setSelected(false);
            checkJubilado.setSelected(false);
            lbTarifa.setText("200");
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 50;
            tarifa -= descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }
        if (btnMerco.isSelected() && !checkEstudiante.isSelected()) {
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 50;
            tarifa += descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }


    }//GEN-LAST:event_checkEstudianteMouseClicked

    private void checkBrasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBrasilMouseClicked
        if (btnMerco.isSelected() && checkBrasil.isSelected()) {
            checkEstudiante.setSelected(false);
            checkJubilado.setSelected(false);
            lbTarifa.setText("200");
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 50;
            tarifa += descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }
        if (btnMerco.isSelected() && !checkBrasil.isSelected()) {
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 50;
            tarifa -= descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }
    }//GEN-LAST:event_checkBrasilMouseClicked

    private void checkJubiladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkJubiladoMouseClicked

        if (btnMerco.isSelected() && checkJubilado.isSelected()) {
            checkEstudiante.setSelected(false);
            checkBrasil.setSelected(false);
            lbTarifa.setText("200");
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 100;
            tarifa -= descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }
        if (btnMerco.isSelected() && !checkJubilado.isSelected()) {
            int tarifa = Integer.valueOf(lbTarifa.getText());
            int descuento = 100;
            tarifa += descuento;
            lbTarifa.setText(String.valueOf(tarifa));
        }


    }//GEN-LAST:event_checkJubiladoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnExtran;
    private javax.swing.ButtonGroup btnGrupos;
    private javax.swing.JRadioButton btnLocal;
    private javax.swing.JRadioButton btnMerco;
    private javax.swing.JCheckBox checkBrasil;
    private javax.swing.JCheckBox checkEstudiante;
    private javax.swing.JCheckBox checkJubilado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lbTarifa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTarifa;
    // End of variables declaration//GEN-END:variables
}
